# -*- coding: utf-8 -*-
"""STOCK RETURN PREDICTOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VPBpc3dnp57NTg1oIAwQ7Fn8nKgb7NJP
"""

!pip install yfinance -q

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import yfinance as yf

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import mean_squared_error

TICKER   = "SPY"
PERIOD   = "10y"
INTERVAL = "1d"

raw = yf.download(TICKER, period=PERIOD, interval=INTERVAL, auto_adjust=True, progress=False)

if isinstance(raw.columns, pd.MultiIndex):
    raw.columns = raw.columns.droplevel(1)

df = raw[["Close"]].copy()
df.columns = ["Price"]
df.dropna(inplace=True)

print(f"  Downloaded {len(df):,} rows for {TICKER}  "
      f"({df.index[0].date()} → {df.index[-1].date()})")

# ── Daily log returns ──
df["Return"] = np.log(df["Price"] / df["Price"].shift(1))

df["Lag_1"] = df["Return"].shift(1)
df["Lag_2"] = df["Return"].shift(2)
df["Lag_3"] = df["Return"].shift(3)

df["SMA_10"] = df["Price"].rolling(10).mean()
df["SMA_50"] = df["Price"].rolling(50).mean()
df["SMA10_ratio"] = df["Price"] / df["SMA_10"] - 1   # % deviation from 10-day SMA
df["SMA50_ratio"] = df["Price"] / df["SMA_50"] - 1

df["Vol_20"] = df["Return"].rolling(20).std()
df["Target"] = df["Return"].shift(-1)

df.dropna(inplace=True)

FEATURE_COLS = ["Lag_1", "Lag_2", "Lag_3",
                "SMA10_ratio", "SMA50_ratio", "Vol_20"]

X = df[FEATURE_COLS].values
y = df["Target"].values

print(X.shape)
print(y.shape)

N_SPLITS = 5
tscv     = TimeSeriesSplit(n_splits=N_SPLITS)

rf_params = dict(
    n_estimators=300,
    max_depth=6,
    min_samples_leaf=20,
    max_features=0.6,
    n_jobs=-1,
    random_state=42,
)

cv_rmse   = []
oof_preds = np.full(len(y), np.nan)   # out-of-fold predictions

for fold, (train_idx, val_idx) in enumerate(tscv.split(X), 1):
    X_train, X_val = X[train_idx], X[val_idx]
    y_train, y_val = y[train_idx], y[val_idx]

    model = RandomForestRegressor(**rf_params)
    model.fit(X_train, y_train)

    preds              = model.predict(X_val)
    oof_preds[val_idx] = preds

    fold_rmse = np.sqrt(mean_squared_error(y_val, preds))
    cv_rmse.append(fold_rmse)
    print(f"  Fold {fold}/{N_SPLITS}  |  Val RMSE = {fold_rmse:.6f}")

print(f"\n  Mean CV RMSE : {np.mean(cv_rmse):.6f}")
print(f"  Std  CV RMSE : {np.std(cv_rmse):.6f}")

final_model = RandomForestRegressor(**rf_params)
final_model.fit(X, y)

fi_series = pd.Series(final_model.feature_importances_,
                      index=FEATURE_COLS).sort_values(ascending=False)
print("  Feature importances:")
print(fi_series.to_string())

backtest_mask = ~np.isnan(oof_preds)

bt_returns = df["Return"].values[backtest_mask]
bt_preds   = oof_preds[backtest_mask]
bt_index   = df.index[backtest_mask]

signal         = np.where(bt_preds > 0, 1, -1).astype(float)
strategy_ret   = signal * bt_returns       # daily strategy P&L
benchmark_ret  = bt_returns

def performance_metrics(daily_rets: np.ndarray, label: str) -> dict:
    cum       = np.cumprod(1 + daily_rets)
    total_ret = cum[-1] - 1

    ann_ret   = (1 + total_ret) ** (252 / len(daily_rets)) - 1
    ann_vol   = daily_rets.std() * np.sqrt(252)
    sharpe    = ann_ret / ann_vol if ann_vol > 0 else np.nan

    # Max drawdown
    roll_max  = np.maximum.accumulate(cum)
    drawdowns = (cum - roll_max) / roll_max
    max_dd    = drawdowns.min()

    return {
        "Strategy"       : label,
        "Total Return"   : f"{total_ret:+.2%}",
        "Ann. Sharpe"    : f"{sharpe:.3f}",
        "Max Drawdown"   : f"{max_dd:.2%}",
        "_total_ret"     : total_ret,
        "_sharpe"        : sharpe,
        "_max_dd"        : max_dd,
        "_cum"           : cum,
    }

strat_metrics = performance_metrics(strategy_ret,  "ML Long/Short")
bench_metrics = performance_metrics(benchmark_ret, "Buy & Hold (SPY)")

display_cols = ["Strategy", "Total Return", "Ann. Sharpe", "Max Drawdown"]
perf_table   = pd.DataFrame([strat_metrics, bench_metrics])[display_cols]

print(perf_table.to_string(index=False))

sns.set_theme(style="darkgrid", context="notebook")
PALETTE = {"ML Long/Short": "#00C4FF", "Buy & Hold (SPY)": "#FF6B35"}

fig1, axes = plt.subplots(2, 1, figsize=(13, 9),
                          gridspec_kw={"height_ratios": [3, 1]},
                          facecolor="#0E1117")
fig1.suptitle(f"SPY — ML Long/Short vs. Buy & Hold\n"
              f"(OOF Backtest, TimeSeriesSplit, n_splits={N_SPLITS})",
              color="white", fontsize=14, fontweight="bold", y=1.01)

ax_equity, ax_dd = axes
for ax in axes:
    ax.set_facecolor("#161B22")
    ax.tick_params(colors="white")
    ax.yaxis.label.set_color("white")
    ax.xaxis.label.set_color("white")
    for spine in ax.spines.values():
        spine.set_edgecolor("#30363D")

"""equity"""

for metrics, label in [(strat_metrics, "ML Long/Short"),
                       (bench_metrics, "Buy & Hold (SPY)")]:
    cum = metrics["_cum"]
    ax_equity.plot(bt_index, cum,
                   label=f"{label}  (Sharpe {metrics['_sharpe']:.2f})",
                   color=PALETTE[label], linewidth=1.8, alpha=0.9)

ax_equity.set_ylabel("Portfolio Value (Starting = $1)", color="white")
ax_equity.set_title("Cumulative Equity Curve", color="white", fontsize=11)
ax_equity.legend(framealpha=0.2, labelcolor="white",
                 facecolor="#1C2128", edgecolor="#30363D")
ax_equity.yaxis.set_major_formatter(mticker.FuncFormatter(
    lambda x, _: f"${x:.2f}"))

strat_cum   = strat_metrics["_cum"]
roll_max_s  = np.maximum.accumulate(strat_cum)
strat_dd    = (strat_cum - roll_max_s) / roll_max_s

ax_dd.fill_between(bt_index, strat_dd, 0,
                   color=PALETTE["ML Long/Short"], alpha=0.45)
ax_dd.plot(bt_index, strat_dd,
           color=PALETTE["ML Long/Short"], linewidth=1.0)
ax_dd.set_ylabel("Drawdown", color="white")
ax_dd.set_title("Strategy Drawdown", color="white", fontsize=11)
ax_dd.yaxis.set_major_formatter(mticker.FuncFormatter(
    lambda x, _: f"{x:.1%}"))

fig1.tight_layout()
plt.savefig("equity_curves.png", dpi=150, bbox_inches="tight",
            facecolor="#0E1117")
plt.show()
print("  Saved → equity_curves.png\n")

N_PATHS   = 150
HORIZON   = 120
MC_SEED   = 2024

rng       = np.random.default_rng(MC_SEED)
emp_rets  = strategy_ret

sampled_idx = rng.integers(0, len(emp_rets), size=(HORIZON, N_PATHS))
mc_rets     = emp_rets[sampled_idx]
mc_cum = np.cumprod(1 + mc_rets, axis=0)

sampled_idx = rng.integers(0, len(emp_rets), size=(HORIZON, N_PATHS))
mc_rets     = emp_rets[sampled_idx]
mc_cum = np.cumprod(1 + mc_rets, axis=0)

terminal_vals  = mc_cum[-1, :]
norm_terminal  = (terminal_vals - terminal_vals.min()) / \
                 (terminal_vals.max() - terminal_vals.min() + 1e-12)
cmap           = plt.get_cmap("plasma")

fig2, ax = plt.subplots(figsize=(13, 7), facecolor="#0E1117")
ax.set_facecolor("#161B22")
ax.tick_params(colors="white")
for sp in ax.spines.values():
    sp.set_edgecolor("#30363D")

days_axis = np.arange(1, HORIZON + 1)
for i in range(N_PATHS):
    ax.plot(days_axis, mc_cum[:, i],
            color=cmap(norm_terminal[i]),
            linewidth=0.7, alpha=0.55)

p5   = np.percentile(mc_cum, 5,  axis=1)
p50  = np.percentile(mc_cum, 50, axis=1)
p95  = np.percentile(mc_cum, 95, axis=1)

ax.fill_between(days_axis, p5, p95,
                color="white", alpha=0.06, label="5th–95th pct. band")
ax.plot(days_axis, p50,  color="white",  linewidth=2.2,
        linestyle="--",  label="Median path")
ax.plot(days_axis, p95,  color="#00FF9F", linewidth=1.5,
        linestyle=":",   label="95th pct.")
ax.plot(days_axis, p5,   color="#FF4C61", linewidth=1.5,
        linestyle=":",   label="5th pct.")
ax.axhline(1.0, color="#AAAAAA", linewidth=1.0, linestyle="-",
           alpha=0.5, label="Break-even")

sm = plt.cm.ScalarMappable(cmap=cmap,
                           norm=plt.Normalize(terminal_vals.min(),
                                              terminal_vals.max()))
sm.set_array([])
cbar = fig2.colorbar(sm, ax=ax, pad=0.01)
cbar.set_label("Terminal Portfolio Value ($1 start)",
               color="white", fontsize=10)
cbar.ax.yaxis.set_tick_params(color="white")
plt.setp(cbar.ax.yaxis.get_ticklabels(), color="white")

ax.set_xlabel("Trading Days Forward", color="white", fontsize=11)
ax.set_ylabel("Portfolio Value (Starting = $1)", color="white", fontsize=11)
ax.set_title(f"Monte Carlo Simulation  —  {N_PATHS} Bootstrap Paths  "
             f"|  {HORIZON}-Day Horizon\n"
             f"Sampled from ML Long/Short Empirical Return Distribution",
             color="white", fontsize=13, fontweight="bold")
ax.legend(framealpha=0.25, labelcolor="white",
          facecolor="#1C2128", edgecolor="#30363D", fontsize=9)
ax.yaxis.set_major_formatter(mticker.FuncFormatter(
    lambda x, _: f"${x:.2f}"))

fig2.tight_layout()
plt.savefig("monte_carlo.png", dpi=150, bbox_inches="tight",
            facecolor="#0E1117")
plt.show()
print("  Saved → monte_carlo.png\n")

print("=" * 60)
print("  FINAL SUMMARY")
print("=" * 60)
mc_end_mean   = mc_cum[-1, :].mean()
mc_end_median = np.median(mc_cum[-1, :])
mc_prob_gain  = (mc_cum[-1, :] > 1.0).mean()

print(f"  OOF Backtest rows        : {len(bt_returns):,}")
print(f"  Strategy Total Return    : {strat_metrics['Total Return']}")
print(f"  Strategy Ann. Sharpe     : {strat_metrics['Ann. Sharpe']}")
print(f"  Strategy Max Drawdown    : {strat_metrics['Max Drawdown']}")
print()
print(f"  Monte Carlo ({N_PATHS} paths, {HORIZON}d horizon)")
print(f"  ├─ Mean terminal value   : ${mc_end_mean:.4f}")
print(f"  ├─ Median terminal value : ${mc_end_median:.4f}")
print(f"  └─ Prob. of profit       : {mc_prob_gain:.1%}")
print()
print("  Outputs: equity_curves.png | monte_carlo.png")
print("=" * 60)
print("  ✓ All steps completed successfully.")
print("=" * 60)